name: Practice the all the sections upto Job Artifacts

on:
  workflow_dispatch:
  issues:
    types: opened
  pull_request:
    types: [opened]
    branches:
      - "main"
      - "releases/**"
      - dev
  push:
    branches:
      - "main"
      - "releases/**"
    paths:
      - ".github/workflows/*"

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache the dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-build-${{ hashFiles('**/package.json') }}
      - name: install dependencies
        run: npm ci
      - name: lint the project
        run: npm run lint
  run-test:
    needs: run-lint
    runs-on: ubuntu-latest
    steps:
      - name: Output Event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: Test the project
        run: npm run test
  build:
    needs: run-test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.output-id.outputs.step-output}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build
      - name: Output the .js file
        id: output-id
        run: find dist/assets -name '*.js' -execdir echo 'step-output={}' >> $GITHUB_OUTPUT ';'
      - name: upload the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: explore the files
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: View output files
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: Download the artifacts
        uses: actions/download-artifact@v4
        with:
          name: explore the files
      - name: Output the content
        run: ls
      - name: Deploy the project
        run: echo "Deploying..."
